// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:moviepilot_mobile/modules/login/models/login_profile.dart';
import 'package:moviepilot_mobile/modules/media_detail/models/media_detail_cache.dart';
import 'package:moviepilot_mobile/modules/plugin/models/installed_plugin_model_cache.dart';
import 'package:moviepilot_mobile/modules/plugin/models/plugin_model_cache.dart';
import 'package:moviepilot_mobile/modules/plugin/models/plugin_palette_cache_entry.dart';
import 'package:moviepilot_mobile/modules/search/models/search_history.dart';
import 'package:moviepilot_mobile/modules/site/models/site_icon_cache.dart';
import 'package:moviepilot_mobile/modules/site/models/site_model_cache.dart';
import 'package:moviepilot_mobile/modules/site/models/site_userdata_cache.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(InstalledPluginModelCacheAdapter());
    registerAdapter(LoginProfileAdapter());
    registerAdapter(MediaDetailCacheAdapter());
    registerAdapter(PluginModelCacheAdapter());
    registerAdapter(PluginPaletteCacheEntryAdapter());
    registerAdapter(SearchHistoryEntryAdapter());
    registerAdapter(SiteIconCacheAdapter());
    registerAdapter(SiteModelCacheAdapter());
    registerAdapter(SiteUserDataCacheAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(InstalledPluginModelCacheAdapter());
    registerAdapter(LoginProfileAdapter());
    registerAdapter(MediaDetailCacheAdapter());
    registerAdapter(PluginModelCacheAdapter());
    registerAdapter(PluginPaletteCacheEntryAdapter());
    registerAdapter(SearchHistoryEntryAdapter());
    registerAdapter(SiteIconCacheAdapter());
    registerAdapter(SiteModelCacheAdapter());
    registerAdapter(SiteUserDataCacheAdapter());
  }
}
